sudo: required
services:
  - docker

before_install:
  - docker build -t gagrech/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true gagrech/react-test npm run test -- --coverage

after_success:
  - docker build -t gagrech/multi-client ./client
  - docker build -t gagrech/multi-nginx ./nginx
  - docker build -t gagrech/multi-server ./server
  - docker build -t gagrech/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take the production images and push them to docker hub
  - docker push gagrech/multi-client
  - docker push gagrech/multi-nginx
  - docker push gagrech/multi-server
  - docker push gagrech/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "multi-docker"
  env: "Multidocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-951974670159"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
